on:
    pull_request:
name: test
jobs:
    eslint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run lint
    commit-lint:
      runs-on: ubuntu-latest
      name: Validate all commits
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Conventional Commits Checker
          uses: netodevel/convetional-commits-checker@v1.0.1
          id: commits-check
          with:
            target-branch: ${{ github.event.pull_request.base.ref }}
            current-branch: ${{ github.event.pull_request.head.ref }}
            pattern: '^\s*(feat|fix|ci|chore|docs|test|style|refactor)(\(.{1,}\))?!?: .{1,}$'
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run build
    test:
      timeout-minutes: 15
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          instance:
            - compose-service: shopware
              APP_URL: http://localhost:8011
            - compose-service: shopware-65
              APP_URL: http://localhost:8021
      env:
        APP_URL: ${{ matrix.instance.APP_URL }}
      steps:
      - uses: actions/checkout@v4
      - name: Compose up ${{ matrix.instance.compose-service }} 
        run: docker compose up -d --pull=always --quiet-pull ${{ matrix.instance.compose-service }} 
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests ${{ matrix.instance.compose-service }} 
        run: npx playwright test --repeat-each 4
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.instance.compose-service }} 
          path: test-results/
          retention-days: 7
